### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by qianggenxiadeshuihu** [STMicroelectronics/STBlueMS_Android#1]
Hi, ST

Two main issues here: 
1) You can find dir "STBlueMS_Android/BlueMS/src/main/java/com/st/BlueMS/demos/Cloud/" in the code structure. But in code, the path are referred by "com.st.BlueMS.demos.cloud.something". But it doesn't exist.

2) In "STBlueMS_Android/BlueMS/src/test/java/com/st/BlueMS/demos/Cloud/MqttFeatureListenerQuickStartTest", there is 
import com.st.BlueMS.demos.cloud.IBMWatsonQuickStartFactory.MqttFeatureListenerQuickStart;
But anyway IBMWatsonQuickStartFactory doesn't exist.

**Comment by GiovanniVisentiniST** [comment]
Hi,
Thanks to report the problems. with the new release the include path should be correct.

Regards
Giovanni

**Comment by bdlightner** [comment]
Giovanni,

Not working with Android Studio 3.0:

```
C:\lightner\Bluetooth\BLE\STBlueMS_Android\BlueMS\src\androidTest\java\com\st\BlueMS\demos\TestCloudLogFragment.java
Error:(121, 33) error: cannot find symbol method getDefaultCloudDeviceName(Node)
Error:(122, 27) error: cannot find symbol variable deviceId
Error:Execution failed for task ':BlueMS:compileDebugAndroidTestJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
Information:BUILD FAILED in 42s
```

This is the offending code:

```
    @Test
    public void defaultDeviceIdIsNodeTag(){
        String deviceIdName =
                CloudLogFragment.getDefaultCloudDeviceName(mActivityRule.getActivity().getNode());
        onView(withId(R.id.deviceId)).check(matches(withText(deviceIdName)));
    }    
```

If I comment out the logic inside defaultDeviceIdIsNodeTag() the app immediately stops after connecting to my SensorTile.  The "stock" .apk from the Play Store works just fine.

HELP!
