### ISSUE TITLE
Cannot find symbol method getDefaultCloudDeviceName(Node)

### ISSUE THREAD

**Issue by bdlightner** [STMicroelectronics/STBlueMS_Android#2]
Giovanni,

Not working with Android Studio 3.0:
```
C:\lightner\Bluetooth\BLE\STBlueMS_Android\BlueMS\src\androidTest\java\com\st\BlueMS\demos\TestCloudLogFragment.java
Error:(121, 33) error: cannot find symbol method getDefaultCloudDeviceName(Node)
Error:(122, 27) error: cannot find symbol variable deviceId
Error:Execution failed for task ':BlueMS:compileDebugAndroidTestJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
Information:BUILD FAILED in 42s
```
This is the offending code:
```
    @Test
    public void defaultDeviceIdIsNodeTag(){
        String deviceIdName =
                CloudLogFragment.getDefaultCloudDeviceName(mActivityRule.getActivity().getNode());
        onView(withId(R.id.deviceId)).check(matches(withText(deviceIdName)));
    }    
```
If I comment out the logic inside defaultDeviceIdIsNodeTag() the app immediately stops after connecting to my SensorTile. The "stock" .apk from the Play Store works just fine.

HELP!

**Comment by GiovanniVisentiniST** [comment]
Hi Bruce,

The problem is in a test code, the `getDefaultCloudDeviceName` function is not inside the `CloudLogFragment` class but inside the `MqttClientUtil ` class. My fault.. 
by the way you can remove the method an the app should run without problems. 
The test code doesn't influence the app behaviour.

Please keep the mobile attached to android studio an post the logcat output with the error that crash the app. 
Please attach also the android version and mobile model.

Thanks
Giovanni

**Comment by bdlightner** [comment]
Giovanni,

Thanks for the prompt response!

I figured that the offending code was not really needed.  The Android app is now working fine.  I made changes to what makes up my Android SDK in Android Studio and the app crash disappeared---so I have nothing to show you from "logcat" now.  Here's exactly what I did to your code to get it to compile:
```
    @Test
    public void defaultDeviceIdIsNodeTag(){
        /* String deviceIdName =
                CloudLogFragment.getDefaultCloudDeviceName(mActivityRule.getActivity().getNode());
        onView(withId(R.id.deviceId)).check(matches(withText(deviceIdName))); */
    }  
```
Thank you (and STM) for making this code available.

Best regards,
Bruce
